// Live READ-ONLY smoke test against a real public PR (anonymous, uses a few of the 60 API requests per hour). It never signs in and never posts.
// node smoke.mjs [owner/repo#n]   (default: dotnet/runtime#135064: 6 files, 3 commits, review comments)
import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { serve } from './serve.mjs';
const [repo, num] = (process.argv[2] || 'dotnet/runtime#135064').split('#');
const { srv, port } = await serve();
const br = await chromium.launch({ executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
const p = await (await br.newContext({ viewport: { width: 1600, height: 1000 }, serviceWorkers: 'block' })).newPage();
const errors = []; p.on('pageerror', e => errors.push(e.message));
await p.goto('http://localhost:' + port + '/prview/#/' + repo + '/pull/' + num);
await p.waitForSelector('.row', { timeout: 60000 });
const title = await p.locator('#prhead h1').innerText();
const count = await p.locator('#count').innerText();
const rate = await p.locator('#rate').innerText();
await p.click('#tree .tr[data-path$="LinkTask.cs"]');
await p.waitForSelector('.cm .thread', { timeout: 20000 });
await p.waitForTimeout(800);
assert.equal(await p.locator('#signin-btn').innerText(), 'Sign in');
assert.equal(await p.locator('#win .addc').count(), 0, 'signed out: nothing to post with');
const list = await p.evaluate(async () => { location.hash = '#/?tab=repo&repo=dotnet/runtime'; await new Promise(r => setTimeout(r, 300)); return null; });
await p.waitForSelector('.prrow', { timeout: 30000 });
const listed = await p.locator('.prrow').count();
await p.goBack().catch(() => {});
await p.evaluate(() => { location.hash = '#/dotnet/runtime/pull/135064'; });
await p.waitForSelector('.row', { timeout: 30000 });
await p.screenshot({ path: new URL('../docs/screenshots/live-smoke.png', import.meta.url).pathname });
console.log({ listed, title, count, rate, rows: await p.locator('.row').count(), threads: await p.locator('.cm .thread').count(), errors });
assert.match(title, /ILLink/); assert.match(count, /6 changed files/); assert.ok(listed >= 1, 'the public repo list works anonymously'); assert.deepEqual(errors, []);
await br.close(); srv.close();
console.log('live smoke ok');
